version: '3.8'

services:
  nest-backend:
    container_name: nest-app
    image: nest-api
    build:
      dockerfile: Dockerfile.development
      context: .
    ports:
      - 8080:8080
    env_file:
      - ./.env.development
    environment:
      - APP_DATABASE__HOST=postgres-db
      - APP_DATABASE__PORT=5432
      - APP_APPLICATION__BASE_URL=0.0.0.0

    networks:
      - backend_network
    volumes:
      - ./src:/usr/src/app/src
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    container_name: postgres-db
    image: postgres:16
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=almicapi
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: {}
