services:
  # A Docker web service
  - type: web
    name: almicapi
    env: docker
    repo: https://github.com/TheCre8tor/almic-store-api.git # optional
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (defaults to master)
    rootDir: .
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /api/v1/users/health-check
    envVars:
      - key: APP_DB__USERNAME
        fromDatabase:
          name: almicapi
          property: user
      - key: APP_DB__PASSWORD
        fromDatabase:
          name: almicapi
          property: password
      - key: APP_DB__HOST
        fromDatabase:
          name: almicapi
          property: host
      - key: APP_DB__PORT
        fromDatabase:
          name: almicapi
          property: port
      - key: APP_DB__DATABASE
        fromDatabase:
          name: almicapi
          property: database
      - key: APP_APPLICATION__BASE_URL
        sync: false
      - key: APP_APP__PORT
        value: 3000
      # - key: APP_REDIS__URI
      #   fromService:
      #     type: redis
      #     name: lightning
      #     property: connectionString
      # - key: APP_EMAIL_CLIENT__AUTHORIZATION_TOKEN
      #   sync: false
      # - key: APP_APPLICATION__HMAC_SECRET
      #   sync: false

  # - type: redis
  #   name: lightning
  #   ipAllowList: # required
  #     - source: 0.0.0.0/0
  #       description: everywhere
  #   region: frankfurt
  #   plan: free # optional (defaults to starter)
  #   maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)
databases:
  - name: almicapi
    region: frankfurt
    plan: free
